// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQum76EGBrfmHAPIrvxYEjnoEL3saLz34',
    appId: '1:232200673833:web:19994801bc460759e1da38',
    messagingSenderId: '232200673833',
    projectId: 'thetestapp-8449c',
    authDomain: 'thetestapp-8449c.firebaseapp.com',
    storageBucket: 'thetestapp-8449c.appspot.com',
    measurementId: 'G-G0DFLEYMCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1l22psIU3FJpB3Vfy5RsAAxGyLm3Nz08',
    appId: '1:232200673833:android:a704ba4c347ee890e1da38',
    messagingSenderId: '232200673833',
    projectId: 'thetestapp-8449c',
    storageBucket: 'thetestapp-8449c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkVWCrs6jzKRwgwQNF2XUl0V_zd5y2uUg',
    appId: '1:232200673833:ios:eeea051d09ca9e7fe1da38',
    messagingSenderId: '232200673833',
    projectId: 'thetestapp-8449c',
    storageBucket: 'thetestapp-8449c.appspot.com',
    androidClientId: '232200673833-dea4qklougg4g4e2l4517lvcncha5rmc.apps.googleusercontent.com',
    iosClientId: '232200673833-enon4k6o18etiei6ltg3g3ht4s18n7b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rydex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkVWCrs6jzKRwgwQNF2XUl0V_zd5y2uUg',
    appId: '1:232200673833:ios:eeea051d09ca9e7fe1da38',
    messagingSenderId: '232200673833',
    projectId: 'thetestapp-8449c',
    storageBucket: 'thetestapp-8449c.appspot.com',
    androidClientId: '232200673833-dea4qklougg4g4e2l4517lvcncha5rmc.apps.googleusercontent.com',
    iosClientId: '232200673833-enon4k6o18etiei6ltg3g3ht4s18n7b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rydex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQum76EGBrfmHAPIrvxYEjnoEL3saLz34',
    appId: '1:232200673833:web:6f2a6e3883070b98e1da38',
    messagingSenderId: '232200673833',
    projectId: 'thetestapp-8449c',
    authDomain: 'thetestapp-8449c.firebaseapp.com',
    storageBucket: 'thetestapp-8449c.appspot.com',
    measurementId: 'G-BF18VR60X1',
  );
}
